### ISSUE TITLE
Patrick's Potential ToDo list

### ISSUE THREAD

**Issue by tessam30** [tessam30/Uganda#2]
Instead of the continual bombardment of emails, I thought I'd post the major data tasks on here.  
**Outstanding data processing tasks for Bangladesh LVAM:**
- [ ] Determine mission contact protocols  
- [ ] Contact mission/Richard to request data related to:  
  - [ ] Malaria data over time (Malaria indicator survey) + quarterly bulletin  
  - [ ] Malaria intervention zones  
  - [ ] Spatio-temporal conflict data from the DRG team  
  - [ ] FTF Community Connector Data  
  - [ ] Timber Poaching mobile data  
  - [ ] Spatio-temporal market price data  
  - [ ] HMIS data for health facility-level data  
  - [ ] Education MIS data  
  - [ ] HIV Prevalence  
  - [ ] annual school census data 
- [ ]  QC\QA Tim's Uganda code on GitHub.
- [ ]  Extract relevant national parks, DEM, and river body shapefiles from data dump; Deliver to Brent for use in basemaps and kriging
